name: Deploy

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE_NAME: islamic-text-validator
  # IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/islamic-text-validator
  IMAGE: asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/islamic-text-validator/api
  DATABASE_BUCKET: ${{ secrets.DATABASE_BUCKET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Download database
        run: |
          mkdir -p data/generated
          gcloud storage cp ${{ env.DATABASE_BUCKET }}/data.db data/generated/data.db

      # - name: Configure Docker for GCR
      #   run: gcloud auth configure-docker --quiet

      # - name: Build and push image
      #   run: |
      #     docker build -t "$IMAGE:${{ github.sha }}" -t "$IMAGE:latest" .
      #     docker push "$IMAGE:${{ github.sha }}"
      #     docker push "$IMAGE:latest"

      - name: Docker build and config
        run: |-
          gcloud builds submit --tag $IMAGE:${{ github.sha }} .


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE:${{ github.sha }}" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars DB_PATH=/app/data/generated/data.db
